In [1]:
import numpy as np

# --- 1. Создание массивов ---
data_list = [10, 20, 30, 40, 50]
arr_from_list = np.array(data_list)

arr_zeros = np.zeros((3, 4))
arr_arange = np.arange(10)

print("Массив из списка:", arr_from_list)
print("Массив нулей:\n", arr_zeros)

# --- 2. Атрибуты ---
print(f"Форма массива нулей (shape): {arr_zeros.shape}")
print(f"Тип данных (dtype): {arr_from_list.dtype}")

# --- 3. Индексирование и срезы ---
element = arr_from_list[2]
print(f"Элемент с индексом 2: {element}")
slice_arr = arr_from_list[1:4]
print(f"Срез [1:4]: {slice_arr}")

# --- 4. Операции и статистика ---
arr_mult = arr_from_list * 2
print(f"Умноженный массив: {arr_mult}")
mean_val = np.mean(arr_from_list)
print(f"Среднее значение: {mean_val}")

Массив из списка: [10 20 30 40 50]
Массив нулей:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Форма массива нулей (shape): (3, 4)
Тип данных (dtype): int64
Элемент с индексом 2: 30
Срез [1:4]: [20 30 40]
Умноженный массив: [ 20  40  60  80 100]
Среднее значение: 30.0
